#InfluxDB: Time series data base container
InfluxSrv:
  image: "tutum/influxdb:0.8.8"
  name: "influxdb"
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor

#cAdvisor: Google Monitoring container
cadvisor:
  image: "google/cadvisor:latest"
  name: "cadvisor"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  links:
    - "InfluxSrv:influxsrv"
  ports:
    - "8080:8080"
  command: "-storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086"

#Grafana: Real-time dashboard desinging container
grafana:
  image: "grafana/grafana:2.0.2"
  name: "grafana"
  ports:
    - "80:3000"
#  environment:
#    - INFLUXDB_HOST=10.0.0.22
#    - INFLUXDB_PORT=8086
#    - INFLUXDB_NAME=cadvisor
#    - INFLUXDB_USER=root
#    - INFLUXDB_PASS=root
#    - HTTP_USER=root
#    - HTTP_PASS=root
  links:
    - "InfluxSrv:influxsrv"

#Shipyard: Graphical dokcer manager
shipyardrethinkdbdata:
  image: "shipyard/rethinkdb"
shipyardrethinkdb:
  image: "shipyard/rethinkdb"
  volumes_from:
    - "shipyardrethinkdbdata"
  ports:
    - "127.0.0.1:49153:8080"
    - "127.0.0.1:49154:28015"
    - "127.0.0.1:29015:29015"
#     - "8080"
#     - "28015"
#     - "29015"

shipyard:
  image: "shipyard/shipyard"
  ports:
    - "8085:8080"
  links:
    - "shipyardrethinkdb:rethinkdb"
    - "shipyardrethinkdbdata"

#Novelty search test fata generation container
noveltyGenerator:
  image: "novelty_generator"
  name: "noveltyGenerator"
  volumes:
    - "/tmp:/tmp"
  command: /bin/bash -c "cp -r /script-generator-for-ffmpeg/ffmpeg/* /tmp/"

#Stress container: ffmpeg compiled with level oO 
versiono0:
  build: "o0"
  cpuset: "0"
  #cpu_shares: 512
  mem_limit: "1000000000"
  #memswap_limit: 10000
  name: "versiono0"
  volumes:
    - "/tmp:/tmp"
  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level o1 
#versiono1:
#  build: "o1"
#  cpuset: "1"
  #cpu_shares: 512
#  mem_limit: "10000000"
  #memswap_limit: 10000
#  name: "versiono1"
#  volumes:
#    - "/tmp:/tmp"
#  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level o2
#versiono2:
#  build: "o2"
#  cpuset: "2"
#  #cpu_shares: 512
#  mem_limit: "10000000"
  #memswap_limit: 10000
#  name: "versiono2"
#  volumes:
#    - "/tmp:/tmp"
#  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level o3 
versiono3:
  build: "o3"
  cpuset: "3"
  #cpu_shares: 512
  mem_limit: "1000000000"
  #memswap_limit: 10000
  name: "versiono3"
  volumes:
    - "/tmp:/tmp"
  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level ofast 
#versionofast:
#  build: "ofast"
#  cpuset: 0,1
  #cpu_shares: 512
#  mem_limit: "10000000"
  #memswap_limit: 10000
#  name: "versionofast"
#  volumes:
#    - "/tmp:/tmp"
#  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level os 
#versionos:
#  build: "os"
#  cpuset: 0,1
#  #cpu_shares: 512
#  mem_limit: 10000000
#  #memswap_limit: 10000
#  name: "versionos"
#  volumes:
#    - "/tmp:/tmp"
#  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

#Stress container: ffmpeg compiled with level og 
#versionog:
#  build: "og"
#  cpuset: 0,1
  #cpu_shares: 512
#  mem_limit: 10000000
#  #memswap_limit: 10000
#  name: "versionog"
#  volumes:
#    - "/tmp:/tmp"
#  command: /bin/bash -c "chmod +x /tmp/ffmpegScript.sh && /tmp/ffmpegScript.sh"

-- INSERT --                                            160,1         Bot
